version: "3"
services:
  fastapi:
    build: .
    volumes:
      - ./catfishio:/code/catfishio
    ports:
      - "8080:8080"
    command: uvicorn catfishio.main:app --host=0.0.0.0 --port=8080 --reload
    depends_on:
      - redis

#  redis:
#    image: redis:7.0.8-alpine
#    ports:
#      - "6379:6379"
