version: "3"
services:
  fastapi:
    build: .
    volumes:
      - ./catfishio:/code/catfishio
    ports:
      - "8080:8080"
    command: uvicorn catfishio.main:app --host=0.0.0.0 --port=8080 --reload
